/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system_gui;

import java.util.ArrayList;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mohammed_Mustafa
 */
public class Match extends javax.swing.JInternalFrame {

    public String time;
    public String date;
    public Stadium stadium;
    public Team team1;
    public Team team2;
    public Referee referee;
    //public ArrayList<Match> List_Match = new ArrayList<>();
    
    public Match(String time, String date, Stadium stadium, Team team1,Team team2, Referee referee) {
        this.time = time;
        this.date = date;
        this.stadium = stadium;
        this.team1 = team1;
        this.team2 = team2;
        this.referee = referee;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }
    
    public void setRef(Referee r){
        this.referee = r;
        
    }
    
    public void setStadium(Stadium s){
        this.stadium = s;
        
    }
    
    public void setTeam1(Team t){
        this.team1 = t;
    }   
    
    public void setTeam2(Team t){
        this.team2 = t;
    }   

    @Override
    public String toString() {
        return time +" "+date+" "+stadium+" "+team1+" "+team2+" "+referee;
    }

    /**
     * Creates new form add
     */
    public Match() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
        
    }
    
    public ArrayList ListMatch(){
        ArrayList<Match> list_match = new ArrayList<>();
        
        Match u1 = new Match("90:30","1/1",stadium,team1,team2,referee);  list_match.add(u1);
        Match u2 = new Match("90:30","1/1",stadium,team1,team2,referee);  list_match.add(u2);
        Match u3 = new Match("90:30","1/1",stadium,team1,team2,referee);  list_match.add(u3);
        Match u4 = new Match("90:30","1/1",stadium,team1,team2,referee);  list_match.add(u4);
        Match u5 = new Match("90:30","1/1",stadium,team1,team2,referee);  list_match.add(u5);
        Match u6 = new Match("90:30","1/1",stadium,team1,team2,referee);  list_match.add(u6); 
       
        return list_match;
      }
    
    public void addRowToJTable(){
          DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
          ArrayList<Match> list_match = ListMatch();
          //ArrayList<Team> list_match = Match.ListMatches();         // to add the match
          Object rowData[] = new Object[5];
          for(int i = 0; i < list_match.size(); i++){
              //rowData[0] = list_match.get(i).;       //  list of matches     t1 Vs t2    
              rowData[1] = list_match.get(i).stadium.ListStadium().get(i);
              rowData[2] = list_match.get(i).referee.ListReferee().get(i);           
              rowData[3] = list_match.get(i).time;    // time of match
              rowData[4] = list_match.get(i).date;    // date of match
              model.addRow(rowData);
          }           
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 3, 48)); // NOI18N
        jLabel1.setText("Match Details");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Team1 Vs Team2", "Stadium", "Referee", "Time", "Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
