/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system_gui;

import java.util.ArrayList;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mohammed_Mustafa
 */
public class Referee extends javax.swing.JInternalFrame {

    private String name_referee;
    private int height;
    private int weight;
    public ArrayList<Referee> list_referee = new ArrayList<>();
    
    public Referee(String name, int height, int weight) {
        this.name_referee = name;
        this.height = height;
        this.weight = weight;
    }

    @Override
    public String getName() {
        return name_referee;
    }

    @Override
    public void setName(String name) {
        this.name_referee = name;
    }

//    public float getHeight() {
//        return height;
//    }

    public void setHeight(int height) {
        this.height = height;
    }

    public float getWeight() {
        return weight;
    }

    public void setWeight(int weight) {
        this.weight = weight;
    }
    
    public ArrayList<Match> getMacthes(ArrayList<Match> list) {
        ArrayList<Match> refMatches = new ArrayList<>();
        for (Match item: list) {
            if (item.referee.getName().toLowerCase().equals(this.getName().toLowerCase())) {
                refMatches.add(item);
            }
        }
        return refMatches;
    }
    
    @Override
    public String toString() {
        return getName()+" "+getHeight()+" "+getWeight();
    }
    /**
     * Creates new form Referee
     */
    public Referee() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);
        
        
        addRowToJTable();
    }
    
    public ArrayList ListReferee(){
        ArrayList<Referee> list_referee = new ArrayList<>();
        
        Referee u1 = new Referee("referee_1",10,10);  list_referee.add(u1);
        Referee u2 = new Referee("referee_2",20,20);  list_referee.add(u2);
        Referee u3 = new Referee("referee_3",30,30);  list_referee.add(u3);
        Referee u4 = new Referee("referee_4",30,30);  list_referee.add(u4);
        Referee u5 = new Referee("referee_5",40,40);  list_referee.add(u5);
        Referee u6 = new Referee("referee_6",40,40);  list_referee.add(u6); 
       
        return list_referee;
      }
    
    public void addRowToJTable(){
          DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
          ArrayList<Referee> list_referee = ListReferee();
          //ArrayList<Team> list_match = Match.ListMatches();         // to add the match
          Object rowData[] = new Object[5];
          for(int i = 0; i < list_referee.size(); i++){
            rowData[0] = list_referee.get(i).name_referee;
            rowData[1] = list_referee.get(i).height;
            rowData[2] = list_referee.get(i).weight;
//            rowData[3] = list_team.get(i).name_team;         //  list of matches      
//            rowData[4] = list_match.get(i).time;             // time of match
//            rowData[5] = list_match.get(i).data;             // date of match
            model.addRow(rowData);
          }           
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Referees Details");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Height", "Weight", "List of MLatches", "Time", "Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
