/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system_gui;

import java.awt.*;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mohammed_Mustafa
 */
public class Team extends javax.swing.JInternalFrame {

    public String name_team;
    public ArrayList<Player> list_player = new ArrayList<>();
    ArrayList<Match> list_teamMatches = new ArrayList<>();
    public int point=0;
    public int win=0;
    public int draw=0;
    public int lose=0;
    public int num_match=3;

    public Team(String name_team) {
        this.name_team = name_team;
    }
    
    public ArrayList<Match> getMatches(ArrayList<Match> list) {
        ArrayList<Match> teamMatches = new ArrayList<>();
        for (Match item: list) {
            if (item.team1.getName().toLowerCase().equals(this.getName().toLowerCase())) {
                teamMatches.add(item);
            }
            else if (item.team2.getName().toLowerCase().equals(this.getName().toLowerCase())) {
                teamMatches.add(item);
            }
        }
        return teamMatches;
    }
    
    @Override
    public String getName() {
        return name_team;
    }

    @Override
    public void setName(String name_team) {
        this.name_team = name_team;
    }

    @Override
    public String toString() {
        return name_team;
    }
    void display_p(Team t){
        if(t.list_player.equals(null))
        {
            System.out.println("the team is empty!!");
        }
        else{
            System.out.println(t.list_player);
        }
        
    }
    
    /**
     * Creates new form Team
     */
    public Team() {
        initComponents();
        addRowToJTable();
        //jLabel2.setLabelFor(Team t);

    }

    public static ArrayList ListTeams(){
        ArrayList<Team> list_team = new ArrayList<>();
        Team u1 = new Team("team_1");  list_team.add(u1);
        Team u2 = new Team("team_2");  list_team.add(u2);
        Team u3 = new Team("team_3");  list_team.add(u3);
        Team u4 = new Team("team_4");  list_team.add(u4);
        
        return list_team;
    }
    
//    public ArrayList ListMatches(){
//        ArrayList<Team> list_team = new ArrayList<Team>();
//        Team u1 = new Team("team_1");
//        Team u2 = new Team("team_2");
//        Team u3 = new Team("team_3");
//        Team u4 = new Team("team_4");
//        list_team.add(u1);
//        list_team.add(u2);
//        list_team.add(u3);
//        list_team.add(u4);
//        return list_team;
//      }
    
      
      public void addRowToJTable(){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        ArrayList<Team> list_team = ListTeams();
        Object rowData[] = new Object[7];
        for(int i = 0; i < list_team.size(); i++)
        {
            rowData[0] = list_team.get(i).name_team;  
            rowData[1] = list_team.get(i).point;
            rowData[2] = list_team.get(i).win;
            rowData[3] = list_team.get(i).draw;
            rowData[4] = list_team.get(i).lose;
            //rowData[5] = list_team.get(i);
            rowData[6] = list_team.get(i).num_match;
            model.addRow(rowData);
        }
                
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Teams Details");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Points", "Win", "Draw", "Lose", "List of Matches", "Number of Matches"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
